#!/bin/bash

cp="-cp lib/*:lib/lwjgl/jar/*:jar/*"

natives="-Djava.library.path=lib/lwjgl/native/linux"
#natives="-Djava.library.path=lib/lwjgl/native/macosx"
#natives="-Djava.library.path=lib/lwjgl/native/solaris"
#natives="-Djava.library.path=lib/lwjgl/native/windows"

memory_min="256m"
memory_max="512m"
memory_min_arg="-Xms$memory_min"
memory_max_arg="-Xms$memory_max"

command="java \
	$cp $natives $memory_min_arg $memory_max_arg \
	kuro.amaktet.Driver $@"

#echo $command
$command
