#lists
#files list
class_files = \
	bin/kuro/amaktet/asset/Cursor.class \
	bin/kuro/amaktet/asset/Sprite.class \
	bin/kuro/amaktet/asset/Tile.class \
	bin/kuro/amaktet/asset/TileSet.class \
	bin/kuro/amaktet/Configuration.class \
	bin/kuro/amaktet/ConsoleManager.class \
	bin/kuro/amaktet/Controller.class \
	bin/kuro/amaktet/Driver.class \
	bin/kuro/amaktet/Game.class \
	bin/kuro/amaktet/game/Cell.class \
	bin/kuro/amaktet/game/Entity.class \
	bin/kuro/amaktet/game/Map.class \
	bin/kuro/amaktet/game/View.class \
	bin/kuro/amaktet/GameExecutionThread.class \
	bin/kuro/amaktet/GameLoader.class \
	bin/kuro/amaktet/Gui.class \
	bin/kuro/amaktet/gui/CustomCardLayout.class \
	bin/kuro/amaktet/math/Dimension3D.class \
	bin/kuro/amaktet/math/Direction.class \
	bin/kuro/amaktet/math/KDimension.class \
	bin/kuro/amaktet/math/KVector.class \
	bin/kuro/amaktet/Render.class \
	bin/kuro/amaktet/res/event/ResourceEvent.class \
	bin/kuro/amaktet/res/event/ResourceListener.class \
	bin/kuro/amaktet/res/JSONResource.class \
	bin/kuro/amaktet/res/Resource.class \
	bin/kuro/amaktet/res/ResourceContainer.class \
	bin/kuro/amaktet/res/ResourceList.class \
	bin/kuro/amaktet/res/ResourceLoadException.class \
	bin/kuro/amaktet/res/TextResource.class \
	bin/kuro/amaktet/res/TextureResource.class \
	bin/kuro/amaktet/ResourceManager.class \
	bin/kuro/amaktet/test/CursorTest.class \
	bin/kuro/amaktet/test/TestConsole.class \
	bin/kuro/amaktet/test/TestInputStreamHandler.class \
	bin/kuro/amaktet/util/Console.class \
	bin/kuro/amaktet/util/event/CommandEvent.class \
	bin/kuro/amaktet/util/event/CommandListener.class \
	bin/kuro/amaktet/util/InputStreamEvent.class \
	bin/kuro/amaktet/util/InputStreamHandler.class \
	bin/kuro/amaktet/util/InputStreamListener.class \
	bin/kuro/amaktet/util/NullOutputStream.class \
	bin/kuro/amaktet/util/Timer.class \
